#!/bin/sh

COMMAND=$1
ERL=`which erl`
ERL_OPTS="-pa deps/*/ebin -pa ebin"
EXEC="$ERL $ERL_OPTS"

## erlang cookie and node name
COOKIE_OPTS=`grep '^-setcookie' vm.args`
NODE=`egrep '^-s?name' vm.args | cut -f2 -d' '`

REBAR=./rebar
REBAR_URL=http://cloud.github.com/downloads/basho/rebar/rebar

case $COMMAND in
	
	start)
		echo "starting ebosh ..."
		$EXEC \
		-args_file vm.args \
		-config ebosh.config \
		-s ebosh \
		-noshell \
		-detached
		;;
		
	console)
		echo "starting ebosh and attaching to debug console..."
		$EXEC \
		-args_file vm.args \
		-config ebosh.config \
		-s ebosh
		;;
	
	restart)
		$0 stop
		$0 start
		;;
	
	stop)
		echo "stopping ebosh ..."
		$EXEC \
		-name "stop-$NODE" \
		$COOKIE_OPTS \
		-eval "rpc:call('$NODE', init, stop, [])" \
		-noshell \
		-hidden \
		-s init stop
		;;
	
	debug)
		echo "entering ebosh debug console ..."
		$EXEC \
		-name "attach-$NODE" \
		$COOKIE_OPTS \
		-remsh $NODE \
		-hidden
		;;
	
	ping)
		echo "pinging $NODE ..."
		$EXEC \
		-name "ping-$NODE" \
		$COOKIE_OPTS \
		-eval \
		"case net_adm:ping('$NODE') of \
			pong -> io:fwrite(\"running~n\",[]); \
			pang -> io:fwrite(\"not running~n\",[]) \
		end" \
		-noshell \
		-hidden \
		-s init stop
		;;
	
	compile)
		$REBAR compile
		$0 compile-mod
		;;
	
	clean)
		$REBAR clean
		;;
	
	test)
		$REBAR skip_deps=true eunit
		;;
	
	doc)
		echo "generating docs"
		$EXEC \
		-name "doc-$NODE" \
		$COOKIE_OPTS \
		-eval \
		"edoc:application( \
			ebosh, \
			\".\", \
			[{doclet, edown_doclet}, \
			 {app_default, \"http://www.erlang.org/doc/man\"}, \
			 {top_level_readme, {\"./README.md\", \"http://github.com/abhinavsingh/ebosh\"}} \
			])" \
		-noshell \
		-hidden \
		-s init stop
		;;
	
	get-deps)
		$REBAR get-deps
		;;
		
	update-deps)
		$REBAR update-deps
		;;
		
	rebar)
		wget -q -O $REBAR $REBAR_URL
		chmod u+x $REBAR
		;;
	
	## compile mod_ebosh for ejabberd
	compile-mod)
		echo "compiling mod_ebosh"
		erlc -I/lib/ejabberd/include -I/lib/ejabberd/include/web -Iinclude -pa /lib/ejabberd/ebin -o ebin/ ejabberd/mod_ebosh.erl
		;;
	
	## install mod_ebosh
	install-mod)
		cp ebin/mod_ebosh.beam /lib/ejabberd/ebin/
		;;
	
	*)
		echo "Usage: $0 {start|console|restart|stop|debug|ping|compile|clean|test|doc|get-deps|update-deps|rebar|compile-mod|install-mod}"
		exit 1
		
esac

exit 0